export class Anunciante{
    alertaSaldoEmail: String
    alertaSaldoMinimo: number
    anuncianteAreaEntregas: any[]
    anuncianteCanalVenda: any[]
    anuncianteChurns: any[]
    anuncianteFormaPagamentos: any[]
    anuncianteParceiroAnunciantes: any[]
    anuncianteParceiroParceiros: any[]
    atendimentoWhatsapp: boolean
    boletos: any[]
    campanhaLotes: any[]
    campanhas: any[]
    celular: String
    cobrancaPorCorreio: boolean
    cobrancaPorEmail: boolean
    comissao: number
    comissaoInfluenciador: number
    deliveryApp: boolean
    desconto: any
    email: String
    emailFeriadoTokens: any[]
    executivo: any
    executivoId: number
    faturaLocal: boolean
    favoritos: any[]
    feriadoEmail: boolean
    feriadoObservacao: String
    feriadoTipoTemplate: number
    fidelidades: any[]
    fiscalBairro: String
    fiscalCep: String
    fiscalCidade: String
    fiscalComplemento: String
    fiscalEmail: String
    fiscalLogradouro: String
    fiscalNumero: String
    fiscalPerfil: number
    fiscalResponsavel: String
    fiscalUf: String
    id: number
    informacoes: String
    inscEstadual: String
    inscMunicipal: String
    locals: any[]
    mostrarConsumidos: boolean
    movimentos: any[]
    nome: String
    nomePagina: String
    notaFiscals: any[]
    observacoes: String
    observacoesFaturamento: String
    optanteSimples: boolean
    patrocinado: boolean
    perfil: any
    perfilId: number
    pessoaResponsavel: String
    preco: number
    pushLogs: any[]
    pushes: any[]
    qtdLocalizacaoIntervalo: number
    razaoSocial: String
    registroCupom: any
    registroNumero: String
    remetente: String
    sedeBairro: String
    sedeCep: String
    sedeCidade: String
    sedeComplemento: String
    sedeLogradouro: String
    sedeNumero: String
    sedeUf: String
    solicitarCupons: boolean
    solicitarCuponsNavigation: any[]
    status: number
    subRegiaoCampanhas: any[]
    subRegiaoLogs: any[]
    tag: any
    tagId: number
    taxaMinima: any
    telefone: String
    telefoneFinanceiro: String
    tempoExpirarExibicao: number
    validacaoSms: String
    website: String
    whatsapp: any
}