export class Campaign
{
    anuncianteId : number 
        titulo :  String
        texto :  String
        qtdTotal : number 
        qtdBaixado : number 
        status : number 
        formato : number 
        valorRef1 : number
        valorRef2 : number
        criadoEm :  Date  
        iniciaEm :  Date 
        finalizaEm :  any 
        expiraEm :  any 
        finalizouEm :  any 
        regra :  String
        regiaoId : number 
        tipoCupom : number 
        tituloCurto :  String
        restritoParceiro :  any 
        ativadoEm :  Date
        aprovadoEm :  any 
        oculta : boolean 
        tipoCampanha : number 
        frequenciaAnuncio : String   
        validadeCupom : String
        patrocinado1 : boolean 
        patrocinado2 : boolean 
        patrocinado3 : boolean 
        patrocinado4 : boolean 
        patrocinado5 : boolean 
        patrocinado6 : boolean 
        flagEspecial :  String  
        pushFavorito : boolean 
        abastMaxDia : number 
        abastNrRecarga : number 
        abastIntervalo : number 
        abastIniciaEm :  any 
        campanhaLoteId : number 
        falhaValidacao : number 
        porcDesconto :  any 
        anunciante :  any 
        campanhaLote :  any 
        regiao :  any 
        boletimDiarios :  any[] 
        campanhaCanalExcluidos :  any[] 
        campanhaLocals :  any[] 
        campanhaS3imgs :  any[] 
        campanhaTags :  any[] 
        cupoms :  any 
        interacaoLocalizacaos :  any[] 
        interacaos :  any[] 
        movimentos :  any[] 
        oferta :  any 
        pushLogs :  any[] 
        pushes :  any[] 
        subRegiaoCampanhas :  any 
        subRegiaoLogs :  any 
        campanhaConsumos :  any[] 
        id : number
}