export class User{
    acessos: any[]
    admin: boolean
    cartaoFraudes: any[]
    cartaoUsos: any[]
    cartaos: any[]
    celular: String
    criadoEm: Date
    cupoms: any[]
    dataChurn: Date
    email: String
    emailAutorizado: boolean
    emailCadastradoEm: Date
    emailNotificacaoCadastral: boolean
    emailRemovidoEm: any
    eventos: any[]
    favoritos: any[]
    fidelidadeBloqueado: boolean
    id: number
    interacaoLocalizacaos: any[]
    interacaos: any[]
    nome: String
    oferta: any[]
    perfils: any[]
    referencia: any
    regiao: any
    regiaoId: number
    reviewSolicitadoEm: Date
    reviewStatus: number
    senhaAlteradaEm: any
    smsAutorizado: boolean
    status: number
    statusChurn: number
}